### ISSUE TITLE
Error when filter and grouping by datetime field

### ISSUE THREAD

**Issue by sugengsuprayogi** [metabase/crate-driver#1]
I'm using

- https://github.com/metabase/crate-driver/releases/download/1.0.0-crate-jdbc-2.3.0/crate.metabase-driver.jar
- running Metabase 0.32.0-snapshot

My Raw Data
![image](https://user-images.githubusercontent.com/5975821/52463403-578f7e80-2ba9-11e9-980f-745db012d8f1.png)

My Aggregation by Time Create
Error : No method in multimethod 'date' for dispatch value: [:crate :day]
![image](https://user-images.githubusercontent.com/5975821/52463451-7d1c8800-2ba9-11e9-8ff6-bb4126cdc813.png)

Errol log
`02-08 13:57:12 ?[1mWARN metabase.query-processor?[0m :: Query failure: No method in multimethod 'date' for dispatch value: [:crate :day]
("--> query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:286)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:278)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:324)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:317)"
 "query_processor$fn__39788$process_query_and_save_execution_BANG___39793$fn__39794.invoke(query_processor.clj:355)"
 "query_processor$fn__39788$process_query_and_save_execution_BANG___39793.invoke(query_processor.clj:341)"
 "query_processor$fn__39814$process_query_and_save_with_max_BANG___39819$fn__39820.invoke(query_processor.clj:387)"
 "query_processor$fn__39814$process_query_and_save_with_max_BANG___39819.invoke(query_processor.clj:382)"
 "api.dataset$fn__43558$fn__43561.invoke(dataset.clj:45)"
 "api.common$fn__24629$invoke_thunk_with_keepalive__24634$fn__24635$fn__24636.invoke(common.clj:435)")
`

**Comment by camsaul** [comment]
Hi @sugengsuprayogi, I pushed a new a new version that fixes this issue. You can get it here https://github.com/metabase/crate-driver/releases/tag/1.0.1-crate-jdbc-2.3.0

**Comment by sugengsuprayogi** [comment]
Thanks @camsaul
